# Generated by Django 5.0.6 on 2025-12-11 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("endereco", models.CharField(blank=True, max_length=255)),
                (
                    "area",
                    models.CharField(
                        blank=True, help_text="Bairro ou região", max_length=120
                    ),
                ),
                ("prioridade_cobertura", models.PositiveSmallIntegerField(default=1)),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["prioridade_cobertura", "nome"],
            },
        ),
        migrations.CreateModel(
            name="PremissasGlobais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton",
                    models.BooleanField(default=True, editable=False, unique=True),
                ),
                (
                    "janela_planejamento_semanas",
                    models.PositiveSmallIntegerField(default=4),
                ),
                ("limite_dobras_semana", models.PositiveSmallIntegerField(default=2)),
                ("limite_horas_semana", models.PositiveSmallIntegerField(default=70)),
                ("politica_revezamento", models.TextField(blank=True)),
                ("confirmacao_diaria", models.BooleanField(default=True)),
                ("observacoes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Premissas globais",
                "verbose_name_plural": "Premissas globais",
            },
        ),
        migrations.CreateModel(
            name="Profissional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "turno_preferencial",
                    models.CharField(
                        blank=True,
                        choices=[("manha", "Manhã"), ("tarde", "Tarde")],
                        max_length=12,
                    ),
                ),
                ("google_calendar_id", models.CharField(blank=True, max_length=255)),
                ("indisponibilidades", models.JSONField(blank=True, default=list)),
                (
                    "carga_semanal_alvo",
                    models.PositiveSmallIntegerField(
                        default=40,
                        help_text="Horas/semana desejadas (máximo recomendado 70h).",
                    ),
                ),
                (
                    "limite_dobras_semana",
                    models.PositiveSmallIntegerField(
                        default=2, help_text="Máximo de dobras permitidas na semana."
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("restricoes", models.TextField(blank=True)),
                ("preferencias", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locais_preferidos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="profissionais_preferidos",
                        to="cadastros.local",
                    ),
                ),
                (
                    "locais_proibidos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="profissionais_proibidos",
                        to="cadastros.local",
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("ativa", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salas",
                        to="cadastros.local",
                    ),
                ),
            ],
            options={
                "ordering": ["local__nome", "nome"],
                "unique_together": {("local", "nome")},
            },
        ),
        migrations.CreateModel(
            name="CapacidadeSala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[("manha", "Manhã"), ("tarde", "Tarde")], max_length=12
                    ),
                ),
                ("capacidade", models.PositiveSmallIntegerField(default=1)),
                ("restricoes", models.TextField(blank=True)),
                ("data_especial", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacidades",
                        to="cadastros.sala",
                    ),
                ),
            ],
            options={
                "ordering": ["sala__local__nome", "sala__nome", "dia_semana", "turno"],
                "unique_together": {("sala", "dia_semana", "turno", "data_especial")},
            },
        ),
    ]
