# Generated by Django 5.0.6 on 2025-12-13 00:00

from django.db import migrations, models


def drop_non_weekly_recurrences(apps, schema_editor):
    CapacidadeSalaEvento = apps.get_model("cadastros", "CapacidadeSalaEvento")
    CapacidadeSala = apps.get_model("cadastros", "CapacidadeSala")

    CapacidadeSalaEvento.objects.all().delete()
    CapacidadeSala.objects.exclude(recorrencia_tipo="semanal").delete()
    CapacidadeSala.objects.filter(recorrencia_tipo="semanal", dia_semana__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0006_alter_capacidadesala_data_especial_and_more"),
    ]

    operations = [
        migrations.RunPython(drop_non_weekly_recurrences, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="capacidadesala",
            name="unica_capacidade_semanal",
        ),
        migrations.RemoveConstraint(
            model_name="capacidadesala",
            name="unica_capacidade_quinzenal",
        ),
        migrations.RemoveConstraint(
            model_name="capacidadesala",
            name="unica_capacidade_mensal_posicional",
        ),
        migrations.RemoveConstraint(
            model_name="capacidadesala",
            name="unica_capacidade_eventual_por_turno",
        ),
        migrations.RemoveConstraint(
            model_name="capacidadesala",
            name="unica_capacidade_data_especial",
        ),
        migrations.RemoveConstraint(
            model_name="capacidadesalaevento",
            name="unica_data_eventual_por_capacidade",
        ),
        migrations.RemoveField(
            model_name="capacidadesala",
            name="data_especial",
        ),
        migrations.RemoveField(
            model_name="capacidadesala",
            name="posicao_no_mes",
        ),
        migrations.RemoveField(
            model_name="capacidadesala",
            name="quinzenal_offset",
        ),
        migrations.RemoveField(
            model_name="capacidadesala",
            name="recorrencia_tipo",
        ),
        migrations.DeleteModel(
            name="CapacidadeSalaEvento",
        ),
        migrations.AddConstraint(
            model_name="capacidadesala",
            constraint=models.UniqueConstraint(
                fields=("sala", "dia_semana", "turno"), name="unica_capacidade_semanal"
            ),
        ),
    ]
