# Generated by Django 5.0.6 on 2025-12-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0007_remove_non_weekly_recurrences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capacidadesala",
            name="dia_semana",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Segunda-feira"),
                    (1, "Terça-feira"),
                    (2, "Quarta-feira"),
                    (3, "Quinta-feira"),
                    (4, "Sexta-feira"),
                    (5, "Sábado"),
                    (6, "Domingo"),
                ],
                help_text="Dia da semana da disponibilidade.",
            ),
        ),
    ]
