# Generated by Django 6.0 on 2025-12-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_alter_local_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissional',
            options={'ordering': ['-destacado', 'nome']},
        ),
        migrations.AddField(
            model_name='profissional',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Se aparece no topo da lista'),
        ),
    ]
