# Generated by Django 5.0.6 on 2025-12-17 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0010_alter_local_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_id', models.CharField(help_text='ID do calendário no Google (email do calendar)', max_length=255, unique=True)),
                ('nome', models.CharField(help_text='Ex: "[Tetê Araújo] Nome Profissional"', max_length=200)),
                ('ultima_sync', models.DateTimeField(blank=True, help_text='Última sincronização', null=True)),
                ('source_tag', models.CharField(default='agendador', help_text='Tag para identificar eventos criados pelo sistema', max_length=50)),
                ('pode_publicar', models.BooleanField(default=True, help_text='Se pode publicar eventos nesta agenda')),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profissional', models.ForeignKey(blank=True, help_text='Profissional (null para agenda geral)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendas_google', to='cadastros.profissional')),
            ],
            options={
                'verbose_name': 'Agenda Google',
                'verbose_name_plural': 'Agendas Google',
                'ordering': ['profissional__nome'],
            },
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data da alocação')),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], max_length=12)),
                ('origem', models.CharField(choices=[('sistema', 'Sistema (gerado automaticamente)'), ('manual', 'Manual (entrada manual)'), ('google', 'Google Calendar')], default='sistema', help_text='Origem da alocação', max_length=20)),
                ('status', models.CharField(choices=[('gerado', 'Gerado'), ('revisado', 'Revisado'), ('confirmado', 'Confirmado'), ('ajustado', 'Ajustado manualmente'), ('manual', 'Manual (sábados)')], default='gerado', help_text='Status da alocação', max_length=20)),
                ('inseguranca', models.CharField(choices=[('baixa', 'Baixa (semana atual)'), ('media', 'Média (próximas 2 semanas)'), ('alta', 'Alta (semanas 3-4)')], default='baixa', help_text='Nível de incerteza/insegurança', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadados: pesos da heurística, motivo, autor, etc.')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='cadastros.local')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='cadastros.profissional')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='cadastros.sala')),
            ],
            options={
                'ordering': ['data', 'turno', 'local__nome', 'sala__nome'],
            },
        ),
        migrations.CreateModel(
            name='EventoCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(help_text='ID do evento no Google', max_length=255)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('gravado', 'Gravado no Google'), ('atualizado', 'Atualizado'), ('conflito', 'Conflito detectado'), ('deletado', 'Deletado')], default='gravado', max_length=20)),
                ('origem', models.CharField(choices=[('sistema', 'Sistema (criado pelo agendador)'), ('manual', 'Manual no Google'), ('google', 'Externo Google')], default='sistema', max_length=20)),
                ('data_sync', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dados do evento Google')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='escala.agendagoogle')),
                ('alocacao', models.ForeignKey(blank=True, help_text='Alocação correspondente (se houver)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_google', to='escala.alocacao')),
            ],
            options={
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ExecucaoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('geracao_semanal', 'Geração semanal'), ('confirmacao_diaria', 'Confirmação diária'), ('sync_google', 'Sincronização Google Calendar'), ('publicacao_google', 'Publicação no Google Calendar'), ('replanejamento', 'Replanejamento via prompt')], max_length=30)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('executando', 'Executando'), ('concluido', 'Concluído'), ('erro', 'Erro'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('iniciou_em', models.DateTimeField(auto_now_add=True)),
                ('terminou_em', models.DateTimeField(blank=True, null=True)),
                ('diff_resumo', models.TextField(blank=True, help_text='Resumo das mudanças propostas ou aplicadas')),
                ('log_json', models.JSONField(blank=True, default=dict, help_text='Log estruturado: eventos, erros, métricas')),
                ('autor', models.CharField(blank=True, help_text='job/prompt/manual/usuario', max_length=100)),
            ],
            options={
                'ordering': ['-iniciou_em'],
                'indexes': [models.Index(fields=['-iniciou_em'], name='escala_exec_iniciou_cc0153_idx'), models.Index(fields=['tipo', 'status'], name='escala_exec_tipo_693962_idx')],
            },
        ),
        migrations.CreateModel(
            name='PromptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_texto', models.TextField(help_text='Texto do prompt enviado')),
                ('resposta', models.TextField(blank=True, help_text='Resposta/resultado da execução')),
                ('acao', models.CharField(choices=[('gerar', 'Gerar escala'), ('ajustar', 'Ajustar escala existente'), ('balancear', 'Balancear horas'), ('limpar_futuro', 'Limpar eventos futuros'), ('custom', 'Comando customizado')], default='custom', help_text='Tipo de ação do prompt', max_length=20)),
                ('diff_resumo', models.TextField(blank=True, help_text='Resumo das mudanças propostas')),
                ('publicada', models.BooleanField(default=False, help_text='Se as mudanças foram aprovadas e publicadas')),
                ('autor', models.CharField(blank=True, help_text='Usuário que executou', max_length=100)),
                ('plataforma', models.CharField(blank=True, help_text='Plataforma agêntica usada: codex, claude-code, opencode', max_length=50)),
                ('log_execucao', models.TextField(blank=True, help_text='Log da execução via SSH')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Histórico de Prompt',
                'verbose_name_plural': 'Histórico de Prompts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='escala_prom_created_50ccf4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Troca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data da troca')),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], max_length=12)),
                ('motivo', models.TextField(blank=True, help_text='Motivo da troca')),
                ('origem', models.CharField(default='whatsapp', help_text='Origem da troca: whatsapp, manual, sistema', max_length=50)),
                ('status', models.CharField(choices=[('registrada', 'Registrada'), ('aplicada', 'Aplicada'), ('cancelada', 'Cancelada')], default='registrada', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trocas', to='cadastros.local')),
                ('profissional_destino', models.ForeignKey(help_text='Profissional que assumiu a alocação', on_delete=django.db.models.deletion.CASCADE, related_name='trocas_destino', to='cadastros.profissional')),
                ('profissional_origem', models.ForeignKey(help_text='Profissional que estava alocado originalmente', on_delete=django.db.models.deletion.CASCADE, related_name='trocas_origem', to='cadastros.profissional')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trocas', to='cadastros.sala')),
            ],
            options={
                'ordering': ['-data', 'turno'],
            },
        ),
        migrations.AddIndex(
            model_name='alocacao',
            index=models.Index(fields=['data', 'turno'], name='escala_aloc_data_487b67_idx'),
        ),
        migrations.AddIndex(
            model_name='alocacao',
            index=models.Index(fields=['profissional', 'data'], name='escala_aloc_profiss_1f4de2_idx'),
        ),
        migrations.AddIndex(
            model_name='alocacao',
            index=models.Index(fields=['status'], name='escala_aloc_status_20df5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='alocacao',
            constraint=models.UniqueConstraint(fields=('sala', 'data', 'turno'), name='unica_alocacao_sala_turno'),
        ),
        migrations.AddIndex(
            model_name='eventocalendar',
            index=models.Index(fields=['data_inicio'], name='escala_even_data_in_25c83b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventocalendar',
            index=models.Index(fields=['agenda', 'data_inicio'], name='escala_even_agenda__de22db_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventocalendar',
            constraint=models.UniqueConstraint(fields=('agenda', 'google_event_id'), name='unico_evento_google_por_agenda'),
        ),
        migrations.AddIndex(
            model_name='troca',
            index=models.Index(fields=['-data'], name='escala_troc_data_e53f63_idx'),
        ),
    ]
